### ISSUE TITLE
无法自动更新

### ISSUE THREAD

**Issue by YixuanWang4** [SamHou2007/mathematical-tool#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YixuanWang4** [comment]
前面一堆叫你如何清晰的报错误的别管，反正就是无法更新

**Comment by SamHou0** [comment]
请现在再试一次，问题是否解决？如果未解决，看到什么错误提示？

**Comment by SamHou0** [comment]
已经调查到是windows7兼容性问题。最新内测版本已经添加了提示，bug即将关闭
